version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - ./config.json:/app/config.json
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
